### ISSUE TITLE
Saving plots 

### ISSUE THREAD

**Issue by caviri** [irmlma/mobility-metrics#1]
Hello @hongyeehh, 

After checking your code in preparation for the component adaptation. I realised that plots are being render using `plt.plot()`.  https://github.com/irmlma/mobility-metrics/blob/da2352b89d8affa729198b947ac012db7c1e1d23/mobmetric/scripts/run_motifs.py#L106 

This is problematic cause when running this component remotely in docker, the rendering won't work. Would be possible to store the figures as `png` files in an output folder?

**Comment by hongyeehh** [comment]
Thanks, @caviri, for taking a look. I have modified the code to store the plots as files in the `.\data\output` folder (will be created if not existing). Please check if any other code functionality needs to be adjusted. Thanks!

**Comment by caviri** [comment]
Great! Thank you @hongyeehh
